### ISSUE TITLE
how would you go about capturing a block comment?

### ISSUE THREAD

**Issue by fponticelli** [typemeta/funcj#8] opened 2018-11-16 03:57 UTC
I am trying to wrap my mind around how to parse the contents of something like the following cases:

```
/* content */
/**/
/***/
```

I tried the followings:

```java
string("/*")
                .andR(Combinators.<Chr>any().many())
                .andL(string("*/"))
```

```java
choice(
        chr('*').andR(notChr('/')).map(v -> "*" + v),
        notChr('*').map(String::valueOf)
)
        .many()
        .between(string("/*"), string("*/"))
```

But no luck.

Thank you for such great library!

**Comment by jon-hanson** [comment] 2018-11-16 10:44
Hi,

I suspect the problem is that if your parser operates directly on the chars (as opposed to a token stream), then this grammar is not LL(1). When the parser encouters a "*" within the comment, it needs to look an extra char ahead to verify that "/" is the following char and therefore we are at the comment end.

One workardound is to first convert the char stream to a token stream, such that "/*" and "*/" become single tokens (e.g. COMMENT_START and COMMENT_END).

Some parsers get around this restriction by allowing backtracking. The problem with this is when the parser encounters an actual syntax error it then backtracks to see if there exists another route, meaning you then lose the location at which the error occurred, and the resultant error message is usually meaningless.

I'll have a play around with this to see whether there are any other solutions.

**Comment by jon-hanson** [comment] 2018-12-11 22:43
Does look somewhat hacky, but if it works...

TBH, i'm not convinced the performance benefits are worth the downsides of making the parser only capable of handling LL(1) grammars.

Regardless, I'll close this issue for now.

**Closed by jon-hanson** 2018-12-11 22:43 UTC

**Comment by fponticelli** [comment] 2018-12-12 23:08
It is totally hacky, I am not proud of it :)

To your original comment, I think I agree ... the performance hit might be minimal and the greater flexibility might be worth it.
