### ISSUE TITLE
Strange behaviour for `choice`

### ISSUE THREAD

**Issue by vbrandl** [typemeta/funcj#23] opened 2020-06-30 13:17 UTC
The `choice` combinator behaves strange for some parsers:

I want to parse either boolean values or words (e.g. identifiers). Each parser on it's own works fine but when combining the boolean and word parser, the parser fails for inputs that start with the same character as any of the boolean values (`true`/`false`).

In the attached example, the first two inputs can be parsed just fine but when parsing and getting the third result, the following exception occurs:

```
Exception in thread "main" java.lang.RuntimeException: Failure at position 2, expected=t
        at org.typemeta.funcj.parser.Result$FailureOnExpected.getOrThrow(Result.java:253)
```

I would expect the parser to try parsing the input as `tr` (for `true`) then find a mismatch, try `f` (for `false`) find another mismatch and in the end parse the input as a word.

```java
static Parser<Chr, Boolean> trueParser() {
    return string("true").map(F.konst(true));
}

static Parser<Chr, Boolean> falseParser() {
    return string("false").map(F.konst(false));
}

static Parser<Chr, Boolean> bool() {
    return choice(trueParser(), falseParser());
}

static Parser<Chr, String> word() {
    return alpha.many1().map(Chr::listToString);
}

static Parser<Chr, Either<Boolean, String>> boolOrWord() {
    return choice(bool().map(Either::left), word().map(Either::right));
}

public static void main(String[] args) {
    final var parser = boolOrWord();
    final var bool = Input.of("true");
    final var anyWord = Input.of("anyword");
    final var startsLikeBool = Input.of("trDEFINITELYSOMETHINGELSE");

    final var parsedTrue = parser.parse(bool).getOrThrow();
    System.out.println(parsedTrue.left());
    System.out.println("assert: " + (parsedTrue.left() == true));

    final var parsedWord = parser.parse(anyWord).getOrThrow();
    System.out.println(parsedWord.right());
    System.out.println("assert: " + parsedWord.right().equals("anyword"));

    final var parsedLikeBool = parser.parse(startsLikeBool).getOrThrow();
    assert parsedLikeBool.right().equals("trDEFINITELYSOMETHINGELSE");
    System.out.println(parsedLikeBool.right());
    System.out.println("assert: " + parsedLikeBool.right().equals("trDEFINITELYSOMETHINGELSE"));
}

```

**Comment by jon-hanson** [comment] 2020-06-30 18:41
The issue is that funcj.parser is a framework for [LL(1) parsers](https://en.wikipedia.org/wiki/LL_parser), meaning parsers for grammars that can be parsed by looking only 1 character ahead at each stage. In your grammar the parser needs to look 5 characters ahead to determine that the token isn't "true" or "false".

You can usually work around this by deferring the decision as to whether the token is a boolean or a word. If I simplify your example for brevity and pretend that a boolean is either "aa" or "bb", then the following illustrates the approach:

    private static Either<Boolean, String> left(boolean value) {
        return Either.left(value);
    }

    private static Either<Boolean, String> right(String value) {
        return Either.right(value);
    }

    static Parser<Chr, Boolean> aa = string("aa").map(F.konst(true));
    static Parser<Chr, Boolean> bb = string("bb").map(F.konst(false));
    static Parser<Chr, Boolean> bool = choice(aa, bb);
    static Parser<Chr, String> word = alpha.many1().map(Chr::listToString);

    static Parser<Chr, Either<Boolean, String>> trueOrWord =
            chr('a').andR(Combinators.any())
                    .map(c -> c.equals('a') ? left(true) : right("a" + c));

    static Parser<Chr, Either<Boolean, String>> falseOrWord =
            chr('b').andR(Combinators.any())
                    .map(c -> c.equals('b') ? left(false) : right("a" + c));

    static Parser<Chr, Either<Boolean, String>> boolOrWord =
            choice(trueOrWord, falseOrWord, word.map(Either::right));

    public static void main(String[] args) {
        final var parser = boolOrWord;
        final var bool = Input.of("aa");
        final var anyWord = Input.of("zz");
        final var startsLikeBool = Input.of("ab");

        final var parsedTrue = parser.parse(bool).getOrThrow();
        System.out.println(parsedTrue.left());
        System.out.println("assert: " + (parsedTrue.left() == true));

        final var parsedWord = parser.parse(anyWord).getOrThrow();
        System.out.println(parsedWord.right());
        System.out.println("assert: " + parsedWord.right().equals("zz"));

        final var parsedLikeBool = parser.parse(startsLikeBool).getOrThrow();
        assert parsedLikeBool.right().equals("ab");
        System.out.println(parsedLikeBool.right());
        System.out.println("assert: " + parsedLikeBool.right().equals("ab"));
    }

**Comment by vbrandl** [comment] 2020-07-02 15:08
So in general a grammar like mine, which is not uniquely decidable, cannot be parsed by a LL(1) parser (my parsers and compilers course was 3 years ago so I don't remember in detail...)

Requiring words that are not boolean values to be wrapped in `""` might fix the ambiguity, too?

**Comment by jon-hanson** [comment] 2020-07-03 09:54
You grammar in its current form is not an LL(1) grammar. The wikipedia [page](https://en.wikipedia.org/wiki/LL_parser#Solutions_to_LL(1)_Conflicts) includes some strategies for resolving this. Alternatively, as you suggest, you can change the language syntax to make it more amenable to be being expressed in an LL(1) grammar, though most languages would lean towards putting the arbitrary string in quotes and leaving true and false as unquoted keywords. Another approach might be to tokenise the input first, and then have the parser operate on word tokens.

**Comment by vbrandl** [comment] 2020-07-07 14:40
Thanks for the refreshing on some theoretical concepts :)

I think for now I'll take the lazy solution and do something like

```java
alpha.many1().map(Chr::listToString).map(s -> {
  if (s.equals("true"))
    return Either.left(true);
  else if (s.equals("false"))
    return Either.left(false);
  else
    return Either.right(s);
})
```

But I might fix that in later™

**Closed** 2020-07-13 11:07 UTC
